### ISSUE TITLE
[Feature Request]: To show the description or the elaboration of the quote when clicked.

### ISSUE THREAD

**Issue by Prathamesh0901** [JayShukla8/Quotes#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Whenever we click on a quote it would be great if we get its meaning in detail. This would let the readers truly get the sense of the quote.

I am willing to work on this feature.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Thanks @Prathamesh0901 , but this type of enhancement is not required as of now.
