### ISSUE TITLE
When dark mode is enabled, at top heading Quotes is not visible properly.

### ISSUE THREAD

**Issue by RAVICHANDRALS507** [JayShukla8/Quotes#105]
@JayShukla8 

I want to work on this issue can you assign me this issue

**Issue**
* When the Dark mode is enabled the Heading Quotes is not visible properly because of the color black.

**Proposed Method**
* Change the color of the that heading so that when the dark mode is enabled the heading should be visible.

![image](https://github.com/user-attachments/assets/8f5667ec-6785-42ad-aa5e-67ce4ffdf261)

**Comment by Samyak137** [comment]
I want to work on that, will you please assign it to me.

**Comment by RAVICHANDRALS507** [comment]
@Samyak137 The Issue is already fixed check the issue no #106
