### ISSUE TITLE
[Feature Request]: Adding copied icon after quote has been copied to clipboard

### ISSUE THREAD

**Issue by Priyadarshan-coder** [JayShukla8/Quotes#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Here is the image of the feature i am proposing..
![Screenshot 2024-10-03 220755](https://github.com/user-attachments/assets/86aa654f-6e34-4022-a8ed-6d59e8d7cbbc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Priyadarshan-coder** [comment]
Please assign this to me

**Comment by Priyadarshan-coder** [comment]
I haved fixed it please accept it under hacktoberfest

**Comment by Samyak137** [comment]
I want to work on that will you please assign it to me.

**Comment by JayShukla8** [comment]
already completed!
