### ISSUE TITLE
Styling 🎨

### ISSUE THREAD

**Issue by JayShukla8** [JayShukla8/Quotes#12]
Styling ideas welcome! Do comment before pull request.

**Comment by JollyJolli** [comment]
It would be cool to add dark mode

**Comment by JayShukla8** [comment]
yes, any ideas on how we can implement it?

**Comment by KorryKatti** [comment]
I can do that , should i do a pr for it ?

**Comment by JayShukla8** [comment]
Ok then, I'll assign both of you this issue. Try and add a button like sun/moon beside the GitHub icon to switch between dark and light mode if you can.

**Comment by KorryKatti** [comment]
i was gonna with a simple text button approach but will try for the sun moon

**Comment by KorryKatti** [comment]
done , please review

**Comment by paridhi1509** [comment]
hi @JayShukla8 
I would like to work on improving the UI by making some changes in the colors and the fonts to make it overall more appealing since the light on light contrast is too sober.

**Comment by JayShukla8** [comment]
@paridhi1509 go ahead. Also try and work on the dark theme too if you don't mind.

**Comment by paridhi1509** [comment]
sure i'll get to it

**Comment by paridhi1509** [comment]
@JayShukla8  i have created a PR please check.

**Comment by kingsmen732** [comment]
i have made some toggling to the design part making it randomise and look more like bento style 
![image](https://github.com/user-attachments/assets/697cd993-e3d2-42ee-b8a6-da2f37a9bf10)
assign this issue with Me so ill make a PR to push

**Comment by kingsmen732** [comment]
@JayShukla8 
also suggest me some changes if you want to be added to this

**Comment by JayShukla8** [comment]
Hi @kingsmen732 , thanks for your efforts, but we prefer the website as it is now. Sorry for that.

**Comment by paridhi1509** [comment]
hey!
@JayShukla8  did you review the changes i made?

**Comment by JayShukla8** [comment]
Hi @paridhi1509 , I did review! Please check #39 and make changes accordingly.

**Comment by paridhi1509** [comment]
@JayShukla8  Can you specify the changes?

**Comment by JayShukla8** [comment]
@paridhi1509 
please check #39
we can discuss there..
