### ISSUE TITLE
[Feature Request]: Saving liked quotes to local storage

### ISSUE THREAD

**Issue by tanish35** [JayShukla8/Quotes#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The user who is scrolling through this page can like a few quotes which will get stored to their local storage and upon revisiting the site they will still be able to see those quotes

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
you can work on it.
