### ISSUE TITLE
[Bug]: Source text Overlaps with icons container 

### ISSUE THREAD

**Issue by chibuike-19** [JayShukla8/Quotes#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The source text of a quote overlaps with the icons container at the bottom of the quote block. This is as a result of the position absolute set to the icons container. 

### Add ScreenShots

![quotes](https://github.com/user-attachments/assets/74b5b28d-2f69-416a-9e8c-e91fa3a30cca)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Hey! You can work on it if you like. Also can you add a three vertical dots button that opens a container that contains copy, share and sound icons? Keep the heart button outside only. I'll be glad if you can resolve this. Thanks.

**Comment by JayShukla8** [comment]
Thanks! Issue resolved!
