### ISSUE TITLE
[Feature Request]: To display quote of the day.

### ISSUE THREAD

**Issue by palak1008jain** [JayShukla8/Quotes#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Once user enters quote of the day  dialog box will appear 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Hey, as of now, we don't need that feature. You can add your fav quote if you like. Thanks!
