### ISSUE TITLE
[Feature Request]: Can i add a quote

### ISSUE THREAD

**Issue by ketan270** [JayShukla8/Quotes#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a quote

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ketan270** [comment]
Please assign this issue to me!

**Comment by JayShukla8** [comment]
yes do a pr directly. No need to create an issue for adding a quote.
