### ISSUE TITLE
Adding Loggin/Signup Page

### ISSUE THREAD

**Issue by Prachirsh** [JayShukla8/Quotes#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It will make more effective and also you will get kive data of user. Can you assign it to me?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Hey, thanks for checking in.
Your idea is valid but as of now we don't that functionality. You can add your favorite quote though. I'd suggest you to make a new pr for that.
