### ISSUE TITLE
[Bug]: Responsive Navbar

### ISSUE THREAD

**Issue by JayShukla8** [JayShukla8/Quotes#157]
Make the existing navbar responsive so that it can adjust to different screen sizes and avoid overlap.

**Comment by NewtonFernandis** [comment]
Hey @JayShukla8, I will work on this. Can you please assign this to me.

**Comment by n-keerthi-gayathri** [comment]
@JayShukla8 please assign me this

**Comment by NewtonFernandis** [comment]
Hey @n-keerthi-gayathri , you can work on this✌️

**Comment by n-keerthi-gayathri** [comment]
![image](https://github.com/user-attachments/assets/ec448ac2-9351-4072-af90-55033d2b13d0)
@JayShukla8  seems like the navbar is responsive... can you elaborate what need to be done

**Comment by JayShukla8** [comment]
Hey guys, there was some issue in data.json so i updated the repo. Please fork it now and ignore older versions.
as for the navbar, here's one ss for reference.
![image](https://github.com/user-attachments/assets/9134df9c-599b-4228-b49b-0d6b066a74e2)

**Comment by NewtonFernandis** [comment]
@n-keerthi-gayathri You can make it something like this for mobile screens
cc: @JayShukla8 

![localhost_5502_(iPhone 12 Pro)](https://github.com/user-attachments/assets/52ae4f71-f637-4deb-afcc-d1fec9fb12d0)

**Comment by JayShukla8** [comment]
I agree @NewtonFernandis. You guys can work together on it.

**Comment by NewtonFernandis** [comment]
@JayShukla8 @n-keerthi-gayathri I have raised PR
