### ISSUE TITLE
adding footer 

### ISSUE THREAD

**Issue by Madan2468** [JayShukla8/Quotes#16]
hey @JayShukla8 ,

I hope this message finds you well , I would like to add footer for the website which would give it more professional look overall , for your better understanding I am attaching the image of the reference footer which I am taking about. 
<img width="1253" alt="Screenshot 2024-09-29 at 11 07 03 PM" src="https://github.com/user-attachments/assets/dfeaab7c-09c3-41cc-9d37-f19dd731b769">

Thank you for your valuable time.

**Comment by JayShukla8** [comment]
Sure,
but I'd suggest you keep the footer limited to Resources column (a Github icon that links to the repo and a contributors option that links to all contributors.) I don't think we need the legal and follow us columns. If you can do that, I'll merge the pr. ✌🏻

**Comment by Madan2468** [comment]
sure, kindly assign me this issue under Hacktoberfest 2024

**Comment by Shreyashahu** [comment]
Sounds good! Could you please assign this task to me as well? I'll make the updates and let you know once the PR is ready.

**Comment by Shreyashahu** [comment]
Sounds good! @JayShukla8 Could you please assign this task to me as well? I'll make the updates and let you know once the PR is ready. Thanks!

**Comment by JayShukla8** [comment]
Ok, both of you can work on it. We'll merge the better looking one.

**Comment by anshika-75** [comment]
I have added a footer that complements the design of the website. The footer includes essential elements such as contact information, acknowledgments, and a "Thanks for visiting" message. This addition enhances the overall user experience by providing important information in a cohesive manner.

@JayShukla8 Please kindly merge my pull request! #16

**Comment by Pariyul** [comment]
Hey , I have to work on that will you please assign it to me.

**Comment by Pariyul** [comment]
kindly assign to me under hacktoberfest

**Comment by Pariyul** [comment]
I already made a PR will you go through it.

**Comment by JayShukla8** [comment]
I'll be closing it now.
