### ISSUE TITLE
[Feature Request]: Making the dropdown in navbar attractive.

### ISSUE THREAD

**Issue by taneeshaa15** [JayShukla8/Quotes#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It is looking too simple according to website, I will make it look good.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by taneeshaa15** [comment]
@JayShukla8 Please assign me this issue under hacktoberfest.

**Comment by JayShukla8** [comment]
also @taneeshaa15 , I don't think every tag is being fetched from the data.json in the dropdown. Like there's "violence" in data.json but not in the dropdown. Can you look at that too if you're comfortable?

**Comment by taneeshaa15** [comment]
@JayShukla8 I did that too, look into it please and add hacktoberfest tag also.

**Comment by JayShukla8** [comment]
Hii @taneeshaa15 , thanks for your work but it seems there are a lot of bugs in your code. _Attaching a video for reference._ If you really want to contribute, you can just add your fav quote and I'll merge it. Also if you are going to work on this navbar again, I suggest you don't alter it's styling and just work on the dropdown menu. 

https://github.com/user-attachments/assets/e64dbc4a-7455-41bc-9235-c67ab291b5ce

**Comment by JayShukla8** [comment]
I'll be closing this now.
