### ISSUE TITLE
[Feature Request]: Add to Favorites functionality

### ISSUE THREAD

**Issue by Disha-Hati** [JayShukla8/Quotes#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Let users bookmark their favorite quotes that align with them and view them in a personalized list.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Disha-Hati** [comment]
@JayShukla8 can you please assign this issue to me?

**Comment by JayShukla8** [comment]
Hi, thanks for your interest but this feature is not needed as of right now.
