### ISSUE TITLE
[Feature Request]: Add "Osho" quote.

### ISSUE THREAD

**Issue by taneeshaa15** [JayShukla8/Quotes#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Quote by osho.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by taneeshaa15** [comment]
@JayShukla8 Please assign me this issue under hacktoberfest.

**Comment by JayShukla8** [comment]
done!
