### ISSUE TITLE
[Feature Request] : Add quotes on Self love

### ISSUE THREAD

**Issue by Tanishka023** [JayShukla8/Quotes#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Quotes on Self love 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Tanishka023** [comment]
Please assign this issue to me under hacktoberfest!

**Comment by JayShukla8** [comment]
done!
