### ISSUE TITLE
[Feature Request]: Add "David Viscott" quote.

### ISSUE THREAD

**Issue by reyansh8104** [JayShukla8/Quotes#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add david viscott quote on love.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by reyansh8104** [comment]
@JayShukla8 Please assign me this issue under hacktoberfest.

**Comment by JayShukla8** [comment]
see #178
