### ISSUE TITLE
[Feature Request]: Improvement of dropdown in navbar.

### ISSUE THREAD

**Issue by reyansh8104** [JayShukla8/Quotes#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will improve the dropdown in navbar and will make it more attractive.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by reyansh8104** [comment]
@JayShukla8 Please assign me this issue under hacktoberfest.

**Comment by JayShukla8** [comment]
refer issue #167
