### ISSUE TITLE
[Feature Request]: Improve Scroll Bar and Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [JayShukla8/Quotes#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

###  Description 

The current Scroll bar Ui has a very basic layout and outdated design and site Loading has no preloader. The screen becomes blank when the website loads. Enhancing the colour scheme of Thumb and Track, improving the preloader and modernizing the scroll bar design would greatly improve the user experience and website presentation

**Describe the solution you'd like**

- Redesign the Scroll bar and preloader for better visual appeal.
- Improving the scroll bar thump and track.
- Improving the preloader.

**Describe alternatives you've considered**

**Without Preloader and without improvement in Scroll BAR**

![Screenshot 2024-10-07 135253](https://github.com/user-attachments/assets/2b9ec426-7248-4938-99dc-2392b7e779f0)

https://github.com/user-attachments/assets/47378d83-5413-4422-9d5d-e7ac479d41c0

**Preloader Mockup**

https://github.com/user-attachments/assets/581ba556-6358-4767-88ee-db82b2b33997

**Additional context**
@JayShukla8   can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
ok sure, mockup looks good.

**Comment by VidhanThakur09** [comment]
thank you for assigning this issue to me , can you please add levels 2 or level 3 labels

**Comment by JayShukla8** [comment]
"gssoc-ext level 2" together or just "level 2"?

**Comment by VidhanThakur09** [comment]
"gssoc-ext level 2" together 

![Screenshot 2024-10-17 111432](https://github.com/user-attachments/assets/efab9358-73a2-479f-8289-0cbe53ba77fd)
like this

And @JayShukla8 Could you please assign me to this issue?
