### ISSUE TITLE
[Bug]: Some tags are not fetched.

### ISSUE THREAD

**Issue by taneeshaa15** [JayShukla8/Quotes#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Every tag is not being fetched from the data.json in the dropdown

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by taneeshaa15** [comment]
@JayShukla8 Please assign me this issue under hacktobefest.

**Comment by JayShukla8** [comment]
done!
