### ISSUE TITLE
[Bug]: Replace Animated Shadows with Zoom-in Hover Effect

### ISSUE THREAD

**Issue by Shreyhac** [JayShukla8/Quotes#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, when hovering over quote cards in the UI (as shown in the attached screenshot), an animated shadow effect appears. The enhancement request is to replace this effect with a subtle zoom-in effect when the user hovers over a card.

Expected Behavior:

When a user hovers over any quote card, the card should zoom in slightly to emphasize the hover state.
The zoom-in effect should be smooth and subtle to maintain a clean aesthetic.
The zoom should occur on the card itself, ensuring that text or icons within the card remain legible and in position.

Implementation Details:

Add CSS transitions to the hover state of each quote card.
The zoom-in scale should be approximately 1.05x to 1.1x.
Ensure the transition is smooth (suggested transition duration: 200ms to 300ms).
Ensure the zoom effect works across different screen sizes (responsiveness is important).
Test the effect to ensure there is no distortion or clipping of content within the cards.

### Add ScreenShots

<img width="1457" alt="Screenshot 2024-10-17 at 01 32 43" src="https://github.com/user-attachments/assets/a5212d8f-3a09-4570-b660-2d78970dd39c">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Hi @Shreyhac , thanks for the suggestion but i have tried zoom-in effect earlier and it tends to disorient the page slightly. That is why i stuck with the shadow. You can contribute your fav quote if you want though. ✌️

**Comment by Shreyhac** [comment]
can u please assign me this under hactoberfest , i will try what i can do
