### ISSUE TITLE
[Feature Request]: Updation of color in "quote".

### ISSUE THREAD

**Issue by reyansh8104** [JayShukla8/Quotes#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Changing "quote" color to black in Navbar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by reyansh8104** [comment]
@JayShukla8  please assign me this issue under hacktoberfest.

**Comment by JayShukla8** [comment]
color should be black only in light mode, don't alter the color for the dark mode.

**Comment by reyansh8104** [comment]
@JayShukla8 Sure

**Comment by Blackie360** [comment]
Any beginner friendly Issue that i can work on Sir?

**Comment by JayShukla8** [comment]
no issue as of now @Blackie360 
issue resolved!
