### ISSUE TITLE
[Documentation Update]: Add inline link to CONTRIBUTING to improve accessibility in README.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [JayShukla8/Quotes#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The link to [CONTRIBUTING.md](https://github.com/JayShukla8/Quotes/blob/main/CONTRIBUTING.md) in [README.md](https://github.com/JayShukla8/Quotes/blob/main/README.md) currently is just a plain text making it a 2 step process to go to the CONTRIBUTING file.

https://github.com/JayShukla8/Quotes/blob/cf7da08769d1160cfbb57ec8074e2c42f3c7b738/README.md?plain=1#L7

### Suggested Change

Adding an inline link for the same will improve accessibility.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
see #186
