### ISSUE TITLE
[Feature Request]: Add a new quote

### ISSUE THREAD

**Issue by shreya-paul-17** [JayShukla8/Quotes#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a new section : fun within which I would like to add some quotes
Kindly assign me this task @JayShukla8 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Hey! Thanks but we don't require any new section on our webpage. You can add your favorite quote if you want with tags like fun, humor, etc.

**Comment by shreya-paul-17** [comment]
Sure @JayShukla8 I will then a new quote under tags of  fun and humor. Then can you please assign me this task under hacktoberfest.

**Comment by shreya-paul-17** [comment]
Can you please add the `hacktoberfest` label @JayShukla8

**Comment by Samyak137** [comment]
Can you please assign it to me.
