### ISSUE TITLE
ADDING NAVBAR AND ALL THE OTHER FACTORS

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [JayShukla8/Quotes#20]
RIGHT NOW, ITS JUST AN SINGLE PAGE APPLICATION I JUST WANT TO CREATE SOME BEAUTIFUL NAVBARE, THROUGH THIS WE CAN MOVE SOME DIFFERENT PAGES.

PLS ASSIGN ME THIS TASK THROUGH THE HACTOBER_FEST TAG

**Comment by JayShukla8** [comment]
no need for a navbar as of now, try and work on tags issue #21
