### ISSUE TITLE
[Feature Request]:  Add Kenyan quotes 

### ISSUE THREAD

**Issue by Blackie360** [JayShukla8/Quotes#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add quotes  by famous Kenyans 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
1 quote only.
