### ISSUE TITLE
[Feature Request]: Add Quotes about Trust.

### ISSUE THREAD

**Issue by reyansh8104** [JayShukla8/Quotes#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding more quote about trust because less data is present.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by reyansh8104** [comment]
@JayShukla8 Please assign me this issue under hacktoberfest.

**Comment by JayShukla8** [comment]
Sorry, contri limited to 1 pr for quotes only.
