### ISSUE TITLE
Add Tags to Quotes for Easier Searching + Search Functionality

### ISSUE THREAD

**Issue by Shreyashahu** [JayShukla8/Quotes#21]
I'd like to suggest an enhancement for the quote system by adding a `tags` field to each quote in the `data.json`. This feature would allow each quote to have context-specific tags, making it easier for users to search by specific topics or themes (e.g. success, courage, motivation).

Proposed Solution:
Each quote in data.json can have an additional tags field, like this:

{
  "quote": "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "author": "Winston Churchill",
  "tags": ["success", "failure", "courage"]
}

This would improve user experience by enabling more relevant search results. I'd be happy to help implement this feature and submit a pull request if approved.

Let me know if you'd like me to proceed!

**Comment by JayShukla8** [comment]
go ahead. but try not to display the tags in the quote card. just keep them so that they help in search functionality.

**Comment by Shreyashahu** [comment]
@JayShukla8 okay. will do!

**Comment by JayShukla8** [comment]
Issue resolved
