### ISSUE TITLE
[Feature Request]: Navbar update

### ISSUE THREAD

**Issue by reyansh8104** [JayShukla8/Quotes#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhancement of "All" Drop down menu in navbar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by reyansh8104** [comment]
@JayShukla8 Please assign me this issue under hacktoberfest.

**Comment by taneeshaa15** [comment]
@JayShukla8 Add hacktoberfest tag also.

**Comment by reyansh8104** [comment]
@JayShukla8  Please add hacktoberfest tag also.
