### ISSUE TITLE
[Feature Request]: pagination

### ISSUE THREAD

**Issue by Istiak-A-Tashrif** [JayShukla8/Quotes#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Showing 15 items per page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Priyadarshan-coder** [comment]
@JayShukla8 can you please assign me this issue under hacktoberfest 2024

**Comment by Istiak-A-Tashrif** [comment]
Its done by me

**Comment by Priyadarshan-coder** [comment]
Okay cool

**Comment by JayShukla8** [comment]
Helli, as of now the scroll bar is just fine. Thanks
