### ISSUE TITLE
[Feature Request]: Improvement of Scroll Bar.

### ISSUE THREAD

**Issue by taneeshaa15** [JayShukla8/Quotes#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improvement of scroll bar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Hi, since hacktoberfest is almost over, I dont have time for new features. But thanks for the idea. Maybe next year✌🏻.
