### ISSUE TITLE
[Bug]: Footer not properly visible and not fixed

### ISSUE THREAD

**Issue by inkerton** [JayShukla8/Quotes#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer should be properly visible and fixed at the bottom .
@JayShukla8 can you assign this issue to me with labels "gssoc-ext" with level 2 and "hacktoberfest-accepted";

### Add ScreenShots

![image](https://github.com/user-attachments/assets/69bffce2-0d7e-49cf-bccb-7c89315d706a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Apply your changes in #219
