### ISSUE TITLE
[Feature Request]: Revamp the toggle button 

### ISSUE THREAD

**Issue by inkerton** [JayShukla8/Quotes#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/ce465d52-bfea-4272-83d5-10636fe2b30e)

I would like to change the toggle button to like

![image](https://github.com/user-attachments/assets/437318ce-59c9-49e2-ac18-0192cc08b422)
OR like 
![image](https://github.com/user-attachments/assets/bbcb4f7a-854b-4c61-bc49-d0fdfc6e523b)
to 
![image](https://github.com/user-attachments/assets/e47a25ad-0e72-4870-bba6-635bfd6212d7)

with proper smooth transition effects .

@JayShukla8 can you assign this issue to me with labels "gssoc-ext" with level 2 and "hacktoberfest-accepted";

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Hi, the buttons as they are right now are just fine. Thanks
