### ISSUE TITLE
[Bug]: The bubble button is not understandable

### ISSUE THREAD

**Issue by inkerton** [JayShukla8/Quotes#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I would like to change the button to resemble more like bubbles like in the SS added with some changes according to the website.

@JayShukla8 can you assign this issue to me with labels "gssoc-ext" with level 2 and "hacktoberfest-accepted";

### Add ScreenShots

FROM 
![image](https://github.com/user-attachments/assets/43f90be8-8a2c-4126-98f3-134871f112f7)
![image](https://github.com/user-attachments/assets/ed0bdec9-258a-4bf8-8b34-eec27a26361c)

TO

![image](https://github.com/user-attachments/assets/f68c3f0d-233b-4813-899e-93621bd10c9d)
![image](https://github.com/user-attachments/assets/50aed118-5da3-4a76-891d-1188a7688919)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
The bubble button as it is now is just fine. Thanks
