### ISSUE TITLE
[Bug]: Fix the car dontent

### ISSUE THREAD

**Issue by inkerton** [JayShukla8/Quotes#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The source and author move up and down as the length of the quote in such cases quotes can either be shown in the center and fix the author, source to bottom of the card.

@JayShukla8 can you assign this issue to me with labels "gssoc-ext" with level 2 and "hacktoberfest-accepted";

### Add ScreenShots

![image](https://github.com/user-attachments/assets/65a78c9c-ec8e-421f-b672-7c347a19f77b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
Thanks but this issue does not need fixing.
