### ISSUE TITLE
Copy and Share Icon with every Quote

### ISSUE THREAD

**Issue by roiveredritesh** [JayShukla8/Quotes#26]
There should be 2 icon needed along with every quote for share on any social plate form and for copying the quotes along with writer name.

**Comment by JayShukla8** [comment]
Can you implement them? Already there's a function that copies the code when clicked on it. See in script.js

**Comment by roiveredritesh** [comment]
@JayShukla8 Yes, I would like to take this issue.

**Comment by TheRaj71** [comment]
Request for Assignment: Adding Share Button to Quotes!!
Hi, I noticed the issue for adding a share button to quotes has already been created. Could you please assign this issue to me? I can implement the feature and ensure it works smoothly.

here's a working implemetnation attached 
![Screenshot 2024-10-02 003127](https://github.com/user-attachments/assets/834d3a10-289d-44a9-844e-50eb65034211)

![Screenshot 2024-10-02 003137](https://github.com/user-attachments/assets/5afe81c9-79b2-4487-b03e-68c07d2f9b6b)

Thank you!
