### ISSUE TITLE
Addition of Quotes API

### ISSUE THREAD

**Issue by anmol420** [JayShukla8/Quotes#34]
Instead of manually adding the quotes in data.json file why not we add an API so that random quotes can be fetched directly from the api instead of individual addition in a file.

If you like my idea, kindly assign me this issue!

**Comment by JayShukla8** [comment]
No bro, the quotes need to be contributed by the users only. Sorry.

**Comment by anmol420** [comment]
So can I write a backend so that user add the quotes to the database using the APi ?

**Comment by JayShukla8** [comment]
ok, i think we can do that. But i don't know much about backend. How do you plan to implement that?

**Comment by anmol420** [comment]
We can add an icon on the UI and the user can click on it and add the quote which will be directly added to our mongodb database which will make our site more interactive. The design of the backend can be easily handled as I have experience in that part and for button and API request from site to the server can be design by the frontend team. 

How's the plan, in this way data.json will not be required to delete (for newbies) and intermediate coders can also add code api fetching and all in the js and html part.

Btw, can you reopen the issue ?

**Comment by JayShukla8** [comment]
ok sure, also I'm new to this so I'll be asking you from time to time. I hope you don't mind.

**Comment by anmol420** [comment]
I won't mind at all sir ! I will add the backend by tomorrow.

**Comment by divy404** [comment]
@JayShukla8 I would like to help him with the frontend part as I have some experience in API fetching. Can you also assign me the issue along with him ? 

@anmol420 Sir I hope you won't have any issues with that!

**Comment by anmol420** [comment]
> @JayShukla8 I would like to help him with the frontend part as I have some experience in API fetching. Can you also assign me the issue along with him ?
> 
> @anmol420 Sir I hope you won't have any issues with that!

@divy404 No issues !

**Comment by JayShukla8** [comment]
wow, i was just thinking about who would handle the frontend!😅

**Comment by anmol420** [comment]
@JayShukla8 Kindly add the Hacktoberfest tag to this issue !
