### ISSUE TITLE
Improve the Navbar

### ISSUE THREAD

**Issue by KanwalpreetSingh1823** [JayShukla8/Quotes#35]
Hi @JayShukla8 . I want to contribute in this project. Please assign this issue to me under Hactoberfest.

**Comment by lakshay102** [comment]
Can I get this issue or someone is already working on this ?

**Comment by JayShukla8** [comment]
what changes are you guys thinking of making?

**Comment by KanwalpreetSingh1823** [comment]
Add background and Sign In / Sign Up buttons ... 

You can give your idea as well ..

**Comment by vverma022** [comment]
Can you assign this issue to me under Hacktoberfest 24.

**Comment by JayShukla8** [comment]
Sorry guys, no need of a navbar as of now. Please check other issue if you want to contribute. #46
