### ISSUE TITLE
Hacktoberfest: Voice Narration

### ISSUE THREAD

**Issue by shubhagarwal1** [JayShukla8/Quotes#43]
Adding a **text-to-speech** feature that reads the quote aloud. This could be beneficial for accessibility and make the site more interactive.
Hi **@JayShukla8** . I want to contribute in this project. Please assign this issue to me under Hactoberfest.

**Comment by gouthamKurapati13** [comment]
Hi @JayShukla8 I can help resolve this issue. Could you assign this task to me under Hactoberfest tag?

**Comment by JayShukla8** [comment]
@shubhagarwal1 hii, you can work on it.
@gouthamKurapati13 you can help too
please coordinate with each other.
