### ISSUE TITLE
Add Dockerfile 

### ISSUE THREAD

**Issue by vverma022** [JayShukla8/Quotes#44]
I would like to add a Dockerfile for the project so that users can containerise the application and run them on any machine. Can I be assigned this issue under **Hacktoberfest '24**

**Comment by roiveredritesh** [comment]
@vverma022 Is docker file required for this project? This is a simple html, js project.

**Comment by vverma022** [comment]
> @vverma022 Is docker file required for this project? This is a simple html, js project.

It'll help the project for the future and also help in deployment. Further enhancements to the project can be easily integrated etc.

**Comment by roiveredritesh** [comment]
> > @vverma022 Is docker file required for this project? This is a simple html, js project.
> 
> It'll help the project for the future and also help in deployment. Further enhancements to the project can be easily integrated etc.

In this stage, I don't think docker file is required. Currently they only showing static data, even doesn't have any backend or scrapper service.
