### ISSUE TITLE
Styling: Fix Dark Theme| Background & Styling | 'Quotes' and Github icon

### ISSUE THREAD

**Issue by akku-07** [JayShukla8/Quotes#46]
![image](https://github.com/user-attachments/assets/28c3c35d-3b53-4b03-b862-778e14c3ebd0)

as you can see here, the dark theme isn't perfect. allow me to change the formatting of  'Quotes' and change the github icon to white

**Comment by JayShukla8** [comment]
can you work on it ?

**Comment by Sujal942** [comment]
Hey I Want to contribute in this can you please assign it to me.

**Comment by deji-ice** [comment]
hi can i contribute to this?

**Comment by Samyak137** [comment]
I Want to contribute in this will you please assign it to me.

**Comment by JayShukla8** [comment]
hello @deji-ice and @Samyak137 , this issue is related to styling and will remain open. You can pr your ideas and i'll merge them if the design is likeable.

**Comment by JayShukla8** [comment]
Issue resolved
