### ISSUE TITLE
Adding a Navigation bar (header)

### ISSUE THREAD

**Issue by Speedysays01** [JayShukla8/Quotes#51]
Please assign me the task under Hacktoberfest 2024.
I could create a simplistic navigation bar containing logo, toggle dark/light mode button and the github icon! This is to ensure that this info always appears on the top of of page for easier navigation and enhanced user experience. I would also make sure to create the navbar responsive to screen size and works good on mobile as well as laptop.

**Comment by JayShukla8** [comment]
ok
sounds good.

**Comment by anshika-75** [comment]
I have created a navbar that enhances the overall design and functionality of the website. The new navbar includes essential features such as a logo, dark/light mode toggle, and github access. I believe this addition improves the user experience significantly.
@JayShukla8 kindly merge my pull request! #51

**Comment by JayShukla8** [comment]
hi @anshika-75 please check #99

**Comment by JayShukla8** [comment]
Issue resolved
