### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [JayShukla8/Quotes#64]
I want to create a seperate contributors pages where user can see all his contributions and also the top contributions 

![image](https://github.com/user-attachments/assets/a123d768-5703-4f75-b5dc-007fb2d1fe3d)

**Comment by JayShukla8** [comment]
Sure.

**Comment by JayShukla8** [comment]
Also can i request you to add a small icon of contributor beside the quote that is being displayed on the home page? That way we can know who contributed which quote.

**Comment by Ayushmaanagarwal1211** [comment]
@JayShukla8 Actually for that i need backend or while adding the quote the contributor needs to add his github profile details because  while adding quote the contributor is only adding quote with author not adding his details so their is no other option to get the profile of the contributor 

![image](https://github.com/user-attachments/assets/b1de005d-a610-47b9-8d7f-40413addf72d)

**Comment by Ayushmaanagarwal1211** [comment]
You can see their is only source author and quote their is no information about the contributor itself 
Hope You understand but in future if backend included i will surely add contributor in the quote

**Comment by JayShukla8** [comment]
True. No worries. Thanks. I'll be closing the issue now.
