### ISSUE TITLE
Authorization feature

### ISSUE THREAD

**Issue by payallenka** [JayShukla8/Quotes#67]
Hi Jay, 
When I saw your project I just saw some random quotes. I really believe if we can add an authorization feature then it will give a more personalized feel as they can have their own personal fav. quotes.   That would make the software even better. For new comers we can have a guest session login with limited features. 

If you are fine with issue please do assign me this issue with the apt. tags.

Regards
Payal Lenka

**Comment by JayShukla8** [comment]
Hii, Thanks for taking out the time.
Yes, I think your idea sounds good. But i see this website as a culmination of contributors fav quotes. So it's just like some kind of art on display you see? But if you can add some feature that allows the admin to edit all the quotes and add/remove them after successful authorization, then that might come in handy. 
I hope I am not confusing you. Hit me up if there are any questions.

**Comment by payallenka** [comment]
yeah, I can built that with admin portal authorization system that will all the CRUD operation rights. If that sounds good do let me know!

**Comment by JayShukla8** [comment]
Hii, that functionality might come in handy. But I might take some time to merge the pr (maybe after oct). So take your time and no need to hurry. If you want to contribute in hacktoberfest, you can add a quote that i can merge immediately. (I hope the hacktoberfest guys won't mind this type of contribution.)

**Comment by payallenka** [comment]
sure will do. 
Kindly assign me this issue and then I shall make a PR to merge a new Quote followed by which i'll work on the admin portal and and make a PR once completed .

**Comment by payallenka** [comment]
As discussed I have started working on the authentication system and have current made a PR to merge a new quote as decided.
Kindly merge the PR as I work on the further process.

**Comment by JayShukla8** [comment]
Since you won't be able to work on this issue, I'll close this issue. I too have been busy and I understand. Thanks again.
