### ISSUE TITLE
Adding feature to bookmark quotes 🔖

### ISSUE THREAD

**Issue by anagha-chaudhari** [JayShukla8/Quotes#71]
User could bookmark their favorite quotes, and they would be saved separately. Please assign under Hacktoberfest 2024

**Comment by JayShukla8** [comment]
but wouldn't the user need to be authorized for that first? 
can you expand upon the idea of bookmarking? 
Also, you're welcome to help in these issues #46 #47 #16

**Comment by anagha-chaudhari** [comment]
@JayShukla8 Actually I intended to keep it for the frontend part using local storage, just like how wishlist items are saved in a wishlist. and sure I'd love to help with these issues
