### ISSUE TITLE
Styling for quotes needs to be improved

### ISSUE THREAD

**Issue by Shub95-arch** [JayShukla8/Quotes#72]
# Code Styling Improvement

## Overview
The current styling of the code needs improvement to ensure that elements are displayed in a consistent and uniform manner. This will enhance readability and user experience.

## Goals
- Ensure all code elements have equal spacing and alignment.
- Use consistent font sizes and styles for different elements.
- Improve layout to prevent elements from being misaligned.

## Proposed Changes
1. **Grid Layout**: Implement a grid system to align code blocks uniformly.
2. **Consistent Margins**: Standardize margins and padding for all elements.
3. **Responsive Design**: Ensure that the styling adjusts well to different screen sizes.
4. **Typography**: Choose a uniform font family and size for all text elements.

## Benefits
- Enhanced readability of code blocks.
- Improved visual appeal of the application.
- Better user engagement through a polished interface.

## Conclusion
By implementing these styling improvements, we can ensure that our code displays in a more organized and aesthetically pleasing manner, ultimately benefiting the user experience.

**Comment by shreyajaiswal17** [comment]
@Shub95-arch I want to work on this kindly assign this to me under hactoberfest

**Comment by JayShukla8** [comment]
@Shub95-arch i hope you got the response in the pr.
please refer #46 for styling.
other ideas welcome.

**Comment by Shub95-arch** [comment]
> @Shub95-arch i hope you got the response in the pr. please refer #46 for styling. other ideas welcome.

Yes thanks for your suggestion
