### ISSUE TITLE
Get quotes from famous quotes libraries dynamically

### ISSUE THREAD

**Issue by roiveredritesh** [JayShukla8/Quotes#75]
@JayShukla8 

Currently we are putting our quotes in data.json file and showing on website. Instead of this, why should we get quote from any open api or scrap data from any website. 

I will do that with the help of node.js.

**Comment by JayShukla8** [comment]
@roiveredritesh 
nah, this is just a collection of contributor's favorite quotes so i don't this we need that much data.
