### ISSUE TITLE
[Feature Request]: Adding a Navbar and Extra Page Updates

### ISSUE THREAD

**Issue by TakangNina** [JayShukla8/Quotes#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the project is an SPA but I would like to work on giving it a navbar with other navelements like an about us page and a separate landing page from where the quotes can be viewed... I would create a quotes.html page where all quotes would be under. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by TakangNina** [comment]
Hello @JayShukla8 can you please assign this to me? Well I already did some work on it and would be grateful if you can take a look at my pull request please. Also please can you give it the hacktoberfest tag?

**Comment by JayShukla8** [comment]
Hi @TakangNina , please check #76
