### ISSUE TITLE
[Feature Request]: Add a "Back to Top" Button

### ISSUE THREAD

**Issue by Fahridanaa** [JayShukla8/Quotes#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As the website grows with more quotes, the length of the page increases significantly. To improve user experience and enhance navigation, I propose adding a "Back to Top" button. This feature will allow users to quickly return to the top of the page without the need for excessive scrolling, especially on long pages with many quotes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
sure.

**Comment by Samyak137** [comment]
I want to work on that will you please assign it to me

**Comment by JayShukla8** [comment]
Issue resolved #92
