### ISSUE TITLE
[Feature Request]: Add hover effects on buttons or clickable elements to enhance interactivity.

### ISSUE THREAD

**Issue by harshit69x** [JayShukla8/Quotes#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add hover effects on buttons or clickable elements to make the website more interactive and engaging. When a user hovers over a button, there could be subtle animations like color changes, scaling, or shadows to indicate the element is clickable. This will improve the user experience by providing visual feedback and making the site feel more dynamic and responsive.

@JayShukla8 Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
sure.

**Comment by Samyak137** [comment]
Please assign me this issue.

**Comment by JayShukla8** [comment]
Issue resolved #97
