### ISSUE TITLE
[Feature Request]: Adding an Alert whenever Copy Button is clicked

### ISSUE THREAD

**Issue by harshit69x** [JayShukla8/Quotes#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Adding an Alert whenever Copy Button is clicked
This feature enhancement involves triggering an alert or notification whenever the "Copy" button is clicked. Upon activation, users receive a confirmation message, improving UX by ensuring that the intended action (copying text) was successfully executed. This helps users confirm that their content was copied to the clipboard without having to manually verify it, making the interface more intuitive and responsive. The alert could be implemented through JavaScript's alert() method or by displaying a custom notification UI. 
![image](https://github.com/user-attachments/assets/9a93a41a-7c45-461b-87b6-b435f4b31c9b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by JayShukla8** [comment]
go ahead, keep the alert in line with the website styling.

**Comment by Sujal942** [comment]
Hey I want to Contribute in this Can you please assign it to me.

**Comment by Samyak137** [comment]
I want to work on that,  please will you assign it to me.

**Comment by AnkitLuhar512117** [comment]
@JayShukla8 assign this issue under hacktoberfest2024.

**Comment by harshit69x** [comment]
@AnkitLuhar in the issues its showing the labels but in the PR its not showing i dont know why.

**Comment by AnkitLuhar512117** [comment]
@harshit69x ,if implementation of your code is done then,u have to push the code in the branch and then u have to open the pull request then it will show.

**Comment by harshit69x** [comment]
@AnkitLuhar i have two branches in my forked repo and i have implemented in the 2nd branch and i raised PR by contribute option and its not showing the labels, what should I do?

**Comment by AnkitLuhar512117** [comment]
@harshit69x push code into the main branch,after that your PR NO. will be shown in this issue and both your issue and PR will be connected to each other.

**Comment by harshit69x** [comment]
Okay so first i push the 2nd branch into the main branch of my repo then from there i raise PR for the issue?

**Comment by AnkitLuhar512117** [comment]
@harshit69x here is sample of output you get after succesfully opening the PR,
 
![image](https://github.com/user-attachments/assets/2e837211-a254-488c-801a-96fe56d6a2d2)

**Comment by harshit69x** [comment]
@AnkitLuhar thanks alot:)

**Comment by AnkitLuhar512117** [comment]
@harshit69x welcome brother, OPEN Your PR Successful..

**Comment by Pariyul** [comment]
Hello Sir,  I want to Contribute in this Can you please assign it to me.

**Comment by JayShukla8** [comment]
issue resolved. Button turns to tick when copied.
